name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.0.4

      - name: Gradle Build Action
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: |
            test
            build

      - name: Notify Slack on Failure
        if: always()
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"channel":"#fint-kontroll-builds","text":"Build failed!"}' https://slack.com/api/chat.postMessage
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
